const DRIVE_UPLOAD = "0ALLEXn5U2V9TUk9PVA";
const DRIVE_JOBS = "0AIeO0_u-HWo-Uk9PVA";
const DRIVE_JOBS_2022 = "0AN6yFIGWA7BwUk9PVA";
const DRIVE_JOBS_2023 = "0AAMenQGp1kxlUk9PVA";
const DRIVE_TEST = "1KQngNo0koSeqlqipWhDPKRsfcKfsC1VP";
const DRIVE_TEST_UPLOAD = "1yq8j9kgPwBKVwk23tUgYjb8kcr1hHnEa";

export const folders = {
  DRIVE_UPLOAD,
  DRIVE_JOBS,
  DRIVE_JOBS_2022,
  DRIVE_JOBS_2023,
  DRIVE_TEST,
  DRIVE_TEST_UPLOAD,
}